### PR TITLE
auth/sign in/sign up/ forget password bloc stuff

### LINKED ISSUE #82: 8. Sign In / Sign Up Screens
8.1. Sign in using email use-case: User enters email and password. The credentials are checked on the server (call to server API). If login was successful then user is redirected to home screen. If an error appeared then user sees error message.

8.2. Sign up using google account use-case: User clicks google icon, user google account credentials are checked. Successful result creates an account for the user locally and makes an API call to the server to add new account. User gets redirected to the home screen.

8.3. Sign up using Facebook account use-case: User clicks Facebook icon, user Facebook account credentials are checked. Successful result creates an account for the user locally and makes an API call to the server to add new account. User gets redirected to the home screen.

8.4. Send password reminder use-case: User enters email on the Forgot Password Screen and clicks “Send” button”. A Server API call is made to check if use exists and to send forgot password email. If it is successful user is sees message from the server (like “An email with password reminder was sent to email@mail.com”). If an error appears user see that error.

8.5. Sign up use-case: User fills in the fields on the Sign Up Screen and clicks “Sign Up” button. API request is made to create new user account. If successful then local record for that user is created and user is redirected to home screen. If an error appears then user sees it on the Sign Up Screen.

[E-commerce App Use-Case Description](https://medium.com/@openflutterproject/open-flutter-project-e-commerce-app-use-cases-and-features-6b7414a6e708)

**Within this task you need to do the following:**

1. Pull all data from local database and render it on the screen.

2. At this time mock remote repository calls for fetching data from a local JSON file. The data structure and method names should be taken from [WooCommerce REST API docs](https://woocommerce.github.io/woocommerce-rest-api-docs/#introduction).

### PR DESCRIPTION
**Pull request by exlo89**
### **1. separate bloc files**

Ok, first of all, what do you think about to **separate the bloc files** in a different folder. 
I put the auth bloc, sign in bloc, sign up bloc and forget password bloc in a separate folder.

Let me know what do you think about it?

### **2. token for the user**

I started with the user repository and **added a token variable to the user.**
The idea is to save the token to get all the data from the web.

### **3. summary of little changes**

- create an auth bloc instance in the main
- create a user repository instance in the main
**reason:** to have only one single instance in the whole app

- sign in or sign up trigger the auth bloc 
**reason:** I think it is cleaner to trigger the auth bloc indirectly

I think that's it for now. It is my first open-source project so I hope you find some helpful changes here. 😃

### CODE REVIEW

**Comment by 4seer** [comment]
1. The idea of separating the bloc for sing in / sign up / forgot password is good. **Let`s keep it.**
2. We need to stay within **[flutter clean architecture](https://github.com/ShadyBoukhary/flutter_clean_architecture)** therefore repositories should  be located in **lib/data/local or remote folder** (you can have a fake repo to take data from local json file for now). Take a look at this **[commit](https://github.com/4seer/openflutterecommerceapp/commit/b7a478ddbbcc8c90e0b4a16fe89111973c8cb5e2)** to get an example of repository location.
3. Let`s have separate **use-cases for sign in / sign up / forgot password** for the clean architecture.
4. There is a connected task with list of use-cases https://github.com/4seer/openflutterecommerceapp/issues/82. (Tasks 8.2, 8.4, 8.5). I will assign it to you.
5. We are integrating our app into WooCommerce and we need to make remote requests to their [REST API](https://woocommerce.github.io/woocommerce-rest-api-docs/#introduction). Take a look at this [discussion at stackoverflow about sign in / sign up](https://stackoverflow.com/questions/31364971/endpoint-for-user-login-signup-in-woocommerce-rest-api-v2). We are making it using **mock requests** so you can make a **local json file for response** instead of remote request for now.

**Comment by exlo89** [comment]
I use [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) to store the token. If somebody knows something better let me know. 

I create a storage file for data during runtime. For example, it saves the token for API calls. Is there another way to save data during runtime? Or did somebody better plans to save data?

**Comment by 4seer** [comment]
Please, merge with development branch first.

**Comment by exlo89** [comment]
ok merge done

**Review by 4seer — APPROVED** [review]

**Pull request merged**
